version: "3.7"
services:
  web-server:
    build:
      dockerfile: .Dockerfile
      context: .
    restart: always
    volumes:
      - "./payroll-superadmin-docker/:/var/www/html/"
    ports:
      - "5000:443"
  
